version: '3.5'

services:
  eureka:
    image: springcloud/eureka
    ports:
      - '8761:8761'

#SGQ microservices structure

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sgq-quality-compliance'
      MYSQL_USER: 'sgq'
      MYSQL_PASSWORD: 'sgq'
      MYSQL_ROOT_PASSWORD: 'sgq'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  sgq-api-gateway:
    build:
      context: ../sgq-api-gateway/
      dockerfile: ../sgq-api-gateway/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - eureka
      - sgq-quality-compliance
    restart: unless-stopped

  sgq-quality-compliance:
    build:
      context: ../sgq-quality-compliance/
      dockerfile: ../sgq-quality-compliance/Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/sgq-quality-compliance?useSSL=false"
    depends_on:
      - mysql
      - eureka
    restart: unless-stopped

  sgq-quality-transparence:
    build:
      context: ../sgq-quality-transparence/
      dockerfile: ../sgq-quality-transparence/Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - eureka
      - sgq-api-gateway
      - localstack
    restart: unless-stopped

# External services structure

  cluemock:
    image: clue/json-server
    volumes: 
      - ./clue_mock.json:/data/db.json
    ports:
      - '80:80'

  sgq-compliance-api:
    build:
      context: ../sgq-compliance-api/
      dockerfile: ../sgq-compliance-api/Dockerfile
    ports:
      - '8085:8085'
    depends_on:
      - eureka
      - cluemock
    restart: unless-stopped

volumes:
  my-db: null